### PR TITLE
Update 001b_fit.ipynb

### PR DESCRIPTION
**Pull request by Gokkulnath**
In class DataBunch(): inside \__init__ method:
--> self.device = default_device if self is None else self 
I believe, It is supposed to be  self.device = default_device if device is None else device

### CODE REVIEW

**Comment by stas00** [comment]
Why are we having PRs to change nb_* files when these are autogenerated?

The files start with:
```
        #################################################
        ### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
        #################################################

```
Shouldn't the process be to do PRs only on the source `.ipynb` files and then leaving `nb_*` to be updated every so often, or perhaps we need a commit hook to make it happen automatically when the source file changes?

Otherwise it sounds like a waste of both developer and contributor time. Thoughts?

**Comment by sgugger** [comment]
Oh I didn't pay attention to the fact it was the nb .py file and not the .ipynb.
nb* files should always be updated to reflect the notebooks, so if can make it happen automatically when the source file changes, it would be best.

**Comment by stas00** [comment]
Absolutely. I'm looking into using git hooks to make this happen
automatically.

One first simplest thing to consider is whether we want those
autogenerated files committed in first place? Perhaps it'd be much
simpler to have the user generate them?

git clone ...
cd fastai_v1
tools/build

which will take care of generating .py files and perhaps anything else
we might want to generate in the future?

Thoughts?

**Comment by stas00** [comment]
First step: the autogenerated files now indicate their source, which should help the user to find their way to the file they need to tweak instead.

And a question towards automation: I see that not all `dev_nb/*ipynb` are converted to `.py` and there doesn't seem to be a way/pattern to derive which ones should be converted. Do we need to have a hardcoded list of `dev_nb/*ipynb` we want to convert? 

I DWIM-way would be to derive it with:

`grep -l '#export' 0*ipynb`

except when I do that I get some files that are not under git? on purpose or just they are simply not quite there yet.

**Comment by sgugger** [comment]
For the first question, I think a good test is to try to convert all notebooks beginning with 0 but not generate a python file if there isn't at least once cell marked for export. We only do this when the notebooks are ready, so that's a good test.
For the second question I'm pretty sure it would be best to use a python script, yes.

**Comment by stas00** [comment]
update: Upon more research, other than doing some hackery, git hooks [won't work](https://stackoverflow.com/a/3284360/9201239). So the recommendation is to do: tools/build git commit -a git push So, really, it all comes to us deciding whether its the developer needs to include in her flow an update all autogenerated files, or we don't commit them at all and get the user to do the same on checkout.

**Comment by stas00** [comment]
>  For the first question, I think a good test is to try to convert all notebooks beginning with 0 but not generate a python file if there isn't at least once cell marked for export. We only do this when the notebooks are ready, so that's a good test.

I guess converting won't automatically add them to be git tracked, so it'll still be a developer's responsibility to add those files to git once he deems them ready? Correct? Or should they be added automatically if they aren't already?

**Comment by stas00** [comment]
I also found a neat trick [here](https://stackoverflow.com/a/32511147/9201239)  to have:

    dev_nb/.gitattributes:
    nb_*.py -diff

which will now make those autogenerated files not show up in the output of `git diff`. Yes/no?

**Comment by sgugger** [comment]
Since we can't trust users not to modify the autogenerated files, I'd rather not do this, so we can see the diffs. @jph00 what do you think?

**Comment by jph00** [comment]
Personally I find the diffs rather helpful.

**Comment by stas00** [comment]
another windows related build question: unnecessarily touch(1)ing files will slow down git as it will have to check them all for changes. Can I `lstat()` files on windows to reliably see their modification time?
Basically I want to add  a check that if .ipynb mod time <= .py mod time, skip the autogeneration for that file.

**Comment by stas00** [comment]
thanks for the feedback on hiding autogenerated diffs.

**Comment by jph00** [comment]
I'm not convinced that autogen of nb*.py is helpful. It's not something I've found myself wanting, at least.

Once we've moved things into proper fastai modules I don't think there will be much confusion that the nb*.py modules are the things that should be changed. Just my $0.02.

**Comment by stas00** [comment]
I'm a bit lost at your last comment, Jeremy. I thought you explained earlier that `nb*py` were a thing and it's there to stay (which means they will need to be synced with `.ipynb`, unless you meant something else. Unless you're talking about preferring to not have them autogenerated and to be manually synced?

**Comment by stas00** [comment]
@sgugger, you can now run:

    tools/build

Added by this [change](https://github.com/fastai/fastai_v1/commit/a7ff209fb1392d28e5087127dc7191acb5695b0d).

Let me know whether it works on windows.

**Comment by jph00** [comment]
> I'm a bit lost at your last comment, Jeremy. I thought you explained earlier that nb*py were a thing and it's there to stay (which means they will need to be synced with *.ipynb). Unless you're talking about preferring to not have them autogenerated and to be manually synced?

Sorry for the confusion @stas00 . Yup they're here to stay. But they're not being used as the final modules - just for the development process and for teaching.

Since you can't use the notebooks without the nb modules being up to date, it's not enough to just update them when committing - you have to update them when you change them. So my feeling is adding a hook to update them when you commit isn't really adding anything.

**Comment by stas00** [comment]
Thank you for clarifying that, @jph00. 

As I shared earlier in this thread, convert on commit won't work anyway, but now we have a simple:

    tools/build

which you can run any time one or more notebooks is modified and it'll figure out what `nb_*.py` need to be updated. The developers just need to include it in their workflow before doing commit.

**Pull request merged**
